/**
 * @fileoverview gRPC-Web generated client stub for todoapp.grpc.models
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as service_pb from './service_pb'; // proto import: "service.proto"


export class HelloWorldClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGreet = new grpcWeb.MethodDescriptor(
    '/todoapp.grpc.models.HelloWorld/Greet',
    grpcWeb.MethodType.UNARY,
    service_pb.GreetRequest,
    service_pb.GreetResponse,
    (request: service_pb.GreetRequest) => {
      return request.serializeBinary();
    },
    service_pb.GreetResponse.deserializeBinary
  );

  greet(
    request: service_pb.GreetRequest,
    metadata?: grpcWeb.Metadata | null): Promise<service_pb.GreetResponse>;

  greet(
    request: service_pb.GreetRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.GreetResponse) => void): grpcWeb.ClientReadableStream<service_pb.GreetResponse>;

  greet(
    request: service_pb.GreetRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.GreetResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/todoapp.grpc.models.HelloWorld/Greet',
        request,
        metadata || {},
        this.methodDescriptorGreet,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/todoapp.grpc.models.HelloWorld/Greet',
    request,
    metadata || {},
    this.methodDescriptorGreet);
  }

}

