// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file service.proto (package todoapp.grpc.models, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GreetRequest, GreetResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service todoapp.grpc.models.HelloWorld
 */
export const HelloWorld = {
  typeName: "todoapp.grpc.models.HelloWorld",
  methods: {
    /**
     * @generated from rpc todoapp.grpc.models.HelloWorld.Greet
     */
    greet: {
      name: "Greet",
      I: GreetRequest,
      O: GreetResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

